<?php

namespace Database\Seeders;

use App\Models\Delegate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DelegateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $delegates = [
            ['de-pardieu.com', 'Emmanuel Fatome', 'fatome@de-pardieu.com'],
            ['de-pardieu.com', 'Patrick Jais', 'jais@de-pardieu.com'],
            ['de-pardieu.com', 'Eric Muller', 'muller@de-pardieu.com'],
            ['swlegal.ch', 'Oliver Triebold', 'oliver.triebold@swlegal.ch'],
            ['swlegal.ch', 'George Ayoub', 'george.ayoub@swlegal.ch'],
            ['machadomeyer.com.br', 'Ivandro Maciel Sanchez Junior', 'ij@machadomeyer.com.br'],
            ['tozzinifreire.com.br', 'Karla Lini Maeji', 'kmaeji@tozzinifreire.com.br'],
            ['tozzinifreire.com.br', 'María Elisa Gualandi Verri', 'mverri@tozzinifreire.com.br'],
            ['tozzinifreire.com.br', 'Marcelo Calliari', 'mc@tozzinifreire.com.br'],
            ['tozzinifreire.com.br', 'Clara Serva', 'cpserva@tozzinifreire.com.br'],
            ['tozzinifreire.com.br', 'Silvia Martins de Castro Cunha Zono', 'sccunha@tozzinifreire.com.br'],
            ['tozzinifreire.com.br', 'Oswaldo Dalla Torre', 'odtorre@tozzinifreire.com.br'],
            ['ferrere.com', 'Isabel Laventure', 'ilaventure@ferrere.com'],
            ['demarest.com.br', 'Paulo Coelho da Rocha', 'procha@demarest.com.br'],
            ['estudiorodrigo.com', 'Luis Carlos Rodrigo', 'lcrodrigo@estudiorodrigo.com'],
            ['estudiorodrigo.com', 'Alex Cordova', 'acordova@estudiorodrigo.com'],
            ['estudiorodrigo.com', 'Ursula Zavala', 'uzavala@estudiorodrigo.com'],
            ['ariaslaw.com', 'Diego Gallegos', 'diego.gallegos@ariaslaw.com'],
            ['corrs.com.au', 'Adam Stapledon', 'adam.stapledon@corrs.com.au'],
            ['corrs.com.au', 'Nastasja Suhadolnik', 'nastasja.suhadolnik@corrs.com.au'],
            ['cariola.cl', 'Francisco Illanes', 'fjillanes@cariola.cl'],
            ['cariola.cl', 'Raimundo Moreno', 'rmoreno@cariola.cl'],
            ['rebaza-alcazar.com', 'Maite Colmenter', 'maite.colmenter@rebaza-alcazar.com'],
            ['bdgs-associes.com', 'David Andreani', 'andreani@bdgs-associes.com'],
            ['bdgs-associes.com', 'Kyum Lee', 'lee@bdgs-associes.com'],
            ['bdgs-associes.com', 'Guillaume Jolly', 'jolly@bdgs-associes.com'],
            ['maisto.it', 'Brazzalotto Alberto', 'a.brazzalotto@maisto.it'],
            ['maisto.it', 'Ricci Francesco', 'f.ricci@maisto.it'],
            ['ehernandez.com.pe', 'José Manuel Abastos Gil Vargas', 'jabastos@ehernandez.com.pe'],
            ['ehernandez.com.pe', 'Miyanou Dufour', 'mdufour@ehernandez.com.pe'],
            ['arnoldporter.com', 'Gregory Harrington', 'gregory.harrington@arnoldporter.com'],
            ['osborneclarke.com', 'Ray Berg', 'ray.berg@osborneclarke.com'],
            ['osborneclarke.com', 'Bjorn Hurten', 'bjoern.huerten@osborneclarke.com'],
            ['rimonlaw.com', 'Ricardo Ampudia', 'ricardo.ampudia@rimonlaw.com'],
            ['twobirds.com', 'Joaquín Muñoz', 'joaquin.munoz@twobirds.com'],
            ['twobirds.com', 'Luis Alfonso Fernández Manzano', 'luisalfonso.fernandez@twobirds.com'],
            ['burges-salmon.com', 'Jeremy Dickerson', 'jeremy.dickerson@burges-salmon.com'],
            ['burges-salmon.com', 'Katie Russell', 'katie.russell@burges-salmon.com'],
            ['burges-salmon.com', 'Rupert Weston', 'rupert.weston@burges-salmon.com'],
            ['velo-legal.com', 'Carolina De La Guardia', 'cdelaguardia@velo-legal.com'],
            ['noandt.com', 'Tomohiro Okawa', 'tomohiro_okawa@noandt.com'],
            ['ppulegal.com', 'Rafael Boisset', 'rafael.boisset@ppulegal.com'],
            ['bomchil.com', 'María Victoria Funes', 'victoria.funes@bomchil.com'],
            ['bomchil.com', 'María Corrá', 'mariaines.corra@bomchil.com'],
            ['phrlegal.com', 'Jaime Herrera', 'jaime.herrera@phrlegal.com'],
            ['phrlegal.com', 'Jesús Albarrán', 'jesus.albarran@phrlegal.com'],
            ['lexvalor.com', 'Carlos Coronel', 'ccoronel@lexvalor.com'],
            ['mcolex.com', 'Juan Manuel Iglesias', 'juan.manuel.iglesias@mcolex.com'],
            ['allende.com', 'Carlos Melhem', 'cmelhem@allende.com'],
            ['allende.com', 'Ricardo Aldave', 'raldave@allende.com'],
            ['bakerbotts.com', 'Jennifer Haworth', 'j.haworth.mccandless@bakerbotts.com'],
            ['mqmgld.com', 'Darío Laguado Giraldo', 'dlaguado@mqmgld.com'],
            ['mqmgld.com', 'Juan Manuel De La Rosa', 'jdelarosa@mqmgld.com'],
            ['mqmgld.com', 'Andres Gonzalez', 'agonzalez@mqmgld.com'],
            ['mqmgld.com', 'Jose Miguel Mendonza', 'jmendoza@mqmgld.com'],
            ['mwe.com', 'Lisa Richman', 'lrichman@mwe.com'],
            ['mwe.com', 'David Kiefer', 'dkiefer@mwe.com'],
            ['mwe.com', 'Elena Otero', 'eotero@mwe.com'],
            ['afra.com', 'Luis López Alfaro', 'lopezalfaro@afra.com'],
            ['afra.com', 'Alejandro Enrique Alemán Ferrari', 'aaleman@afra.com'],
            ['guerrero.cl', 'Pedro Lyon', 'plyon@guerrero.cl'],
            ['guerrero.cl', 'César Gálvez', 'cgalvez@guerrero.cl'],
            ['lloredacamacho.com', 'Andrés Hidalgo', 'ahidalgo@lloredacamacho.com'],
            ['lloredacamacho.com', 'Christian Perez-Rueda', 'cperez@lloredacamacho.com'],
            ['eof.com.ar', 'Agustin Siboldi', 'siboldia@eof.com.ar'],
            ['vieirarezende.com.br', 'Camila Borba Lefevre', 'clefevre@vieirarezende.com.br'],
            ['oppenhoff.eu', 'Alf Baars', 'alf.baars@oppenhoff.eu'],
            ['bpvabogados.com', 'Bosco de Gispert', 'bgispert@bpvabogados.com'],
            ['akerman.com', 'Pedro A. Freyre', 'pedro.freyre@akerman.com'],
            ['akerman.com', 'Luis A. Perez', 'luis.perez@akerman.com'],
            ['akerman.com', 'Felicia Leborgne Nowels', 'felicia.nowels@akerman.com'],
            ['akerman.com', 'Arturo H. Banegas M', 'arturo.banegasmasia@akerman.com'],
            ['akerman.com', 'Ildefonso ‘Dito’ P. Mas', 'ildefonso.mas@akerman.com'],
            ['akerman.com', 'Karyn Koiffman', 'karyn.koiffman@akerman.com'],
            ['slaughterandmay.com', 'James Stacey', 'james.stacey@slaughterandmay.com'],
            ['slaughterandmay.com', 'Rebecca Cousin', 'rebecca.cousin@slaughterandmay.com'],
            ['rebaza-alcazar.com', 'Felipe Boisset', 'felipe.boisset@rebaza-alcazar.com'],
            ['rebaza-alcazar.com', 'Alberto Rebaza', 'alberto.rebaza@rebaza-alcazar.com'],
            ['nyc.com.ar', 'María Fraguas', 'mfraguas@nyc.com.ar'],
            ['nyc.com.ar', 'Mariana Guzian', 'mguzian@nyc.com.ar'],
            ['pinsentmasons.com', 'Amaia Rivas Kortazar', 'amaia.rivas@pinsentmasons.com'],
            ['pinsentmasons.com', 'Antonio Sánchez Montero', 'antonio.sanchezmontero@pinsentmasons.com'],
            ['pinsentmasons.com', 'Gonzalo Gil Suarez', 'gonzalo.gil@pinsentmasons.com'],
            ['legance.it', 'Filippo Ruffato', 'fruffato@legance.it'],
            ['wilmerhale.com', 'Danielle Morris', 'danielle.morris@wilmerhale.com'],
            ['bruchoufunes.com', 'Javier Rodríguez Galli', 'javier.rodriguez.galli@bruchoufunes.com'],
            ['bruchoufunes.com', 'Sergio Arbeleche, Minería', 'sergio.arbeleche@bruchoufunes.com'],
            ['bruchoufunes.com', 'Daniela Rey', 'daniela.rey@bruchoufunes.com'],
            ['bruchoufunes.com', 'Ignacio Funes de Rioja', 'ignacio.funes@bruchoufunes.com'],
            ['bruchoufunes.com', 'Alejandro Perelsztein', 'alejandro.perelsztein@bruchoufunes.com'],
            ['bruchoufunes.com', 'José Bazán', 'jose.bazan@bruchoufunes.com'],
            ['bruchoufunes.com', 'Estanislao Olmos', 'estanislao.olmos@bruchoufunes.com'],
            ['darroisvilley.com', 'Carine Dupeyron', 'cdupeyron@darroisvilley.com'],
            ['pillsburylaw.com', 'Sthepan Becker', 'stephan.becker@pillsburylaw.com'],
            ['pillsburylaw.com', 'Charles C. Conrad', 'charles.conrad@pillsburylaw.com'],
            ['pillsburylaw.com', 'Russell DaSilva', 'russell.dasilva@pillsburylaw.com'],
            ['pillsburylaw.com', 'Deborah S. Thoren-Peden', 'deborah.thorenpeden@pillsburylaw.com'],
            ['pillsburylaw.com', 'Nancy A. Fischer', 'nancy.fischer@pillsburylaw.com'],
            ['pillsburylaw.com', 'Carolina A. Fornos', 'carolina.fornos@pillsburylaw.com'],
            ['pillsburylaw.com', 'William Wood', 'william.wood@pillsburylaw.com'],
            ['blplegal.com', 'Luis Castro', 'lcastro@blplegal.com'],
            ['blplegal.com', 'Vittoria Di Gioacchino', 'vdigioacchino@blplegal.com'],
            ['blplegal.com', 'Vivian Liberman', 'vliberman@blplegal.com'],
            ['blplegal.com', 'Jose Alvarez', 'jalvarez@blplegal.com'],
            ['blplegal.com', 'Jorge Arenales', 'jarenales@blplegal.com'],
            ['wadiaghandy.com', 'Denzil Arambhan', 'denzil.arambhan@wadiaghandy.com'],
            ['wadiaghandy.com', 'Pinaz Mehta', 'pinaz.mehta@wadiaghandy.com'],
            ['darroisvilley.com', 'Forrest Alogna', 'falogna@darroisvilley.com'],
            ['darroisvilley.com', 'Hugo Diener', 'hdiener@darroisvilley.com'],
            ['pn.com.br', 'Francisco Maranhão', 'fmaranhao@pn.com.br'],
            ['pn.com.br', 'Marcelo Viveiros de Moura', 'mvmoura@pn.com.br'],
            ['pn.com.br', 'Miguel Tornovsky', 'mtornovsky@pn.com.br'],
            ['pn.com.br', 'Roberta Demange', 'rdemange@pn.com.br'],
            ['houthoff.com', 'David Heems', 'd.heems@houthoff.com'],
            ['houthoff.com', 'Thomas Stouten', 't.stouten@houthoff.com'],
            ['stikeman.com', 'Maxime Turcotte', 'mturcotte@stikeman.com'],
            ['stikeman.com', 'Sophie Lamonde', 'slamonde@stikeman.com'],
            ['apoyoconsultoria.com', 'Eduardo Campos', 'ecampos@apoyoconsultoria.com'],
            ['hsf.com', 'Amal Bouchenaki', 'amal.bouchenaki@hsf.com'],
            ['allende.com', 'Valeriano Guevara Lynch', 'vguevara@allende.com'],
            ['bomchil.com', 'Tomás Araya', 'tomas.araya@bomchil.com'],
            ['marval.com', 'Cecilia Mairal', 'cmm@marval.com'],
            ['marval.com', 'Gustavo Patricio Giay', 'gpg@marval.com'],
            ['marval.com', 'Miguel Del Pino', 'mp@marval.com'],
            ['marval.com', 'Bárbara Ramperti', 'bvr@marval.com'],
            ['marval.com', 'Pablo Artagaveytia', 'paa@marval.com'],
            ['mcolex.com', 'Diego Parise', 'diego.parise@mcolex.com'],
            ['syls.com.ar', 'Rafael Salaberren Dupont', 'rsd@syls.com.ar'],
            ['marval.com', 'Ricardo Ostrower', 'rao@marval.com'],
            ['maddocks.com.au', 'David Newman', 'david.newman@maddocks.com.au'],
            ['corrs.com.au', 'Jane Barrett', 'jane.barrett@corrs.com.au'],
            ['bmalaw.com.br', 'Camila Goldberg', 'cgc@bmalaw.com.br'],
            ['bmalaw.com.br', 'Felipe Galea', 'fes@bmalaw.com.br'],
            ['bmalaw.com.br', 'Francisco Antunes Maciel Müssnich', 'mussnich@bmalaw.com.br'],
            ['cesconbarrieu.com.br', 'Rafael Baleroni', 'rafael.baleroni@cesconbarrieu.com.br'],
            ['demarest.com.br', 'Luciana Tornovsky', 'ltornovsky@demarest.com.br'],
            ['lefosse.com', 'Rodrigo Junqueira', 'rodrigo.junqueira@lefosse.com'],
            ['machadomeyer.com.br', 'Ana Karina E. de Souza', 'anakarinasouza@machadomeyer.com.br'],
            ['veirano.com.br', 'Alberto de Orleans e Bragança', 'alberto.braganca@veirano.com.br'],
            ['veirano.com.br', 'Alex Backsmann', 'alex.backsmann@veirano.com.br'],
            ['veirano.com.br', 'Ana Carolina Barretto', 'ana.barretto@veirano.com.br'],
            ['veirano.com.br', 'Paula Surerus', 'paula.surerus@veirano.com.br'],
            ['veirano.com.br', 'Renata Fialho', 'renata.oliveira@veirano.com.br'],
            ['veirano.com.br', 'Ronaldo Veirano', 'veirano@veirano.com.br'],
            ['cesconbarrieu.com.br', 'Alexandre Barreto', 'alexandre.barreto@cesconbarrieu.com.br'],
            ['cesconbarrieu.com.br', 'Manoela Miranda', 'manoela.miranda@cesconbarrieu.com.br'],
            ['cesconbarrieu.com.br', 'Maurício Barros', 'mauricio.barros@cesconbarrieu.com.br'],
            ['cesconbarrieu.com.br', 'Paulo Macedo', 'paulo.macedo@cesconbarrieu.com.br'],
            ['blg.com', 'Ira Nishisato', 'inishisato@blg.com'],
            ['blg.com', 'Hugh Arthur Meighen', 'hmeighen@blg.com'],
            ['dwpv.com', 'Franziska Ruf', 'fruf@dwpv.com'],
            ['dwpv.com', 'Peter Mendell', 'pmendell@dwpv.com'],
            ['dwpv.com', 'Vincent A. Mercier', 'vmercier@dwpv.com'],
            ['osler.com', 'Matthew Kronby', 'mkronby@osler.com'],
            ['osler.com', 'Lauren Tomasich', 'ltomasich@osler.com'],
            ['osler.com', 'Kelsey Armstrong', 'kearmstrong@osler.com'],
            ['agycia.cl', 'Arnaldo Gorziglia', 'agorziglia@agycia.cl'],
            ['bofillmir.cl', 'Octavio Bofill G', 'obofill@bofillmir.cl'],
            ['bofillmir.cl', 'Pablo Mir', 'pmir@bofillmir.cl'],
            ['carey.cl', 'Juan Francisco Mackenna', 'jfmackenna@carey.cl'],
            ['carey.cl', 'Óscar Aitken', 'oaitken@carey.cl'],
            ['carey.cl', 'Pablo lacobelli', 'piacobelli@carey.cl'],
            ['carey.cl', 'Patricia Silberman', 'psilberman@carey.cl'],
            ['cariola.cl', 'Andrea Saffie', 'asaffie@cariola.cl'],
            ['moralesybesa.cl', 'Carlos Silva', 'csilva@moralesybesa.cl'],
            ['moralesybesa.cl', 'Macarena Laso', 'mlaso@moralesybesa.cl'],
            ['carey.cl', 'Francisca Corti', 'fcorti@carey.cl'],
            ['zhonglun.com', 'Yun Zhou', 'zhouyun@zhonglun.com'],
            ['ppulegal.com', 'Federico Grebe', 'federico.grebe@ppulegal.com'],
            ['ppulegal.com', 'Claudia Barrero', 'claudia.barrero@ppulegal.com'],
            ['ariaslaw.com', 'Andrey Dorado', 'andrey.dorado@ariaslaw.com'],
            ['bustamantefabara.com', 'Jose Rafael Bustamante Crespo', 'jrbc@bustamantefabara.com'],
            ['bustamantefabara.com', 'Juan Felipe Bustamante', 'juanfelipe@bustamantefabara.com'],
            ['bustamantefabara.com', 'Maria Rosa Fabara-Vera', 'mrfabara@bustamantefabara.com'],
            ['pbplaw.com', 'Estefania Lopez Verdu', 'elopez@pbplaw.com'],
            ['pbplaw.com', 'Juan Manuel Marchan', 'jmarchan@pbplaw.com'],
            ['pbplaw.com', 'Sandra Reed Serrano', 'sreed@pbplaw.com'],
            ['bdgs-associes.com', 'Lucile Gaillard', 'gaillard@bdgs-associes.com'],
            ['bredinprat.com', 'José María Pérez', 'josemariaperez@bredinprat.com'],
            ['bredinprat.com', 'Didier Martin', 'didiermartin@bredinprat.com'],
            ['bredinprat.com', 'Marina Weiss', 'marinaweiss@bredinprat.com'],
            ['hengeler.com', 'Hans-Jörg Ziegenhain', 'joerg.ziegenhain@hengeler.com'],
            ['noerr.com', 'Christian C.W. Pleister', 'christian.pleister@noerr.com'],
            ['noerr.com', 'Laurenz Tholen', 'laurenz.tholen@noerr.com'],
            ['advant-beiten.com', 'Oliver Korte', 'oliver.korte@advant-beiten.com'],
            ['advant-beiten.com', 'Christian von Wistinghausen', 'christian.wistinghausen@advant-beiten.com'],
            ['debrauw.com', 'Reinier Kleipool', 'reinier.kleipool@debrauw.com'],
            ['stibbe.com', 'Hans Witteveen', 'hans.witteveen@stibbe.com'],
            ['arnoldporter.com', 'Carlos A. Lobo', 'carlos.lobo@arnoldporter.com'],
            ['foxmandal.in', 'Sushant Shetty', 'sushant.shetty@foxmandal.in'],
            ['khaitanco.com', 'Rabindra Jhunjhunwala', 'rabindra.jhunjhunwala@khaitanco.com'],
            ['belex.com', 'Sir Marco Passalacqua', 'marco.passalacqua@belex.com'],
            ['maisto.it', 'Bavila Alessandro', 'a.bavila@maisto.it'],
            ['chiomenti.net', 'Annalisa Reale', 'annalisa.reale@chiomenti.net'],
            ['mhm-global.com', 'Katsumasa Suzuki', 'katsumasa.suzuki@mhm-global.com'],
            ['mhm-global.com', 'Seiichi Okazaki', 'seiichi.okazaki@mhm-global.com'],
            ['mhm-global.com', 'Kenichi Sekiguchi', 'kenichi.sekiguchi@mhm-global.com'],
            ['nishimura.com', 'Masaru Umeda', 'm.umeda@nishimura.com'],
            ['mhm-global.com', 'Allejah Franco', 'allejah.franco@mhm-global.com'],
            ['noandt.com', 'Tokura Akihiro', 'akihiro_tokura@noandt.com'],
            ['mhm-global.com', 'Tomohiro Tsuchiya', 'tomohiro.tsuchiya@mhm-global.com'],
            ['mhm-global.com', 'Aritsune Miyoda', 'aritsune.miyoda@mhm-global.com'],
            ['mhm-global.com', 'Yohsuke Higashi', 'yohsuke.higashi@mhm-global.com'],
            ['mhm-global.com', 'Aruto Kagami', 'aruto.kagami@mhm-global.com'],
            ['mhm-global.com', 'Nobuhiko Suzuki', 'nobuhiko.suzuki@mhm-global.com'],
            ['lennox.nl', 'Gerard Endedijk', 'gerard.endedijk@lennox.nl'],
            ['akd.nl', 'Erwin Redemakers', 'erademakers@akd.nl'],
            ['akd.nl', 'Sandy Van Leeuwen', 'svanleeuwen@akd.nl'],
            ['icazalaw.com', 'Adolfo Andrés Gonzalez-Ruiz Arias', 'adolfog@icazalaw.com'],
            ['estudiorodrigo.com', 'Luis Enrique Palacios', 'lpalacios@estudiorodrigo.com'],
            ['caseslacambra.com', 'Bojan Radovanovic', 'bojan.radovanovic@caseslacambra.com'],
            ['uria.com', 'Guillermo Canalejo', 'guillermo.canalejo@uria.com'],
            ['wilmerhale.com', 'Maria Camila Hoyos', 'maria.hoyos@wilmerhale.com'],
            ['chiomenti.net', 'Edoardo Canetta Rossi Palermo', 'edoardo.canetta@chiomenti.net'],
            ['cgsh.com', 'Jonathan Kolodner', 'jkolodner@cgsh.com'],
            ['cgsh.com', 'Jorge U. Juantorena', 'jjuantorena@cgsh.com'],
            ['cgsh.com', 'José Manuel Silva', 'msilva@cgsh.com'],
            ['cravath.com', 'Daniel J. Cerqueira', 'dcerqueira@cravath.com'],
            ['debevoise.com', 'Andrew M. Levine', 'amlevine@debevoise.com'],
            ['debevoise.com', 'David Grosgold', 'dgrosgold@debevoise.com'],
            ['dechert.com', 'Alvaro Galindo', 'alvaro.galindo@dechert.com'],
            ['skadden.com', 'Alejandro Gonzalez Lazzeri', 'alejandro.gonzalez.lazzeri@skadden.com'],
            ['skadden.com', 'Brett Fleisher', 'brett.fleisher@skadden.com'],
            ['blankrome.com', 'Cecilia Ibarra-Van Oostenrijk', 'cecilia.ibarra-vanoostenrijk@blankrome.com'],
            ['ropesgray.com', 'Rob Rivollier', 'bob.rivollier@ropesgray.com'],
            ['squairlaw.com', 'Julie Walrafen', 'jwalrafen@squairlaw.com'],
            ['sidley.com', 'Simon Navarro', 'snavarro@sidley.com'],
            ['skadden.com', 'Julie Bédard', 'julie.bedard@skadden.com'],
            ['akerman.com', 'Gabriela Alexander', 'gabriela.alexander@akerman.com'],
            ['cravath.com', 'Timothy G. Cameron', 'tcameron@cravath.com'],
            ['rimonlaw.com', 'Nicolas Lafont', 'nicolas.lafont@rimonlaw.com'],
            ['maddocks.com.au', 'Andrew McNee', 'andrew.mcnee@maddocks.com.au'],
            ['rimonlaw.com', 'Juan Zuñiga', 'juan.zuniga@rimonlaw.com'],
            ['rimonlaw.com', 'Héctor Arangua', 'hector.arangua@rimonlaw.com'],
            ['rimonlaw.com', 'Sean Byrne', 'sean.byrne@rimonlaw.com'],
            ['nelsonmullins.com', 'Lori Anne Czepiel', 'lorianne.czepiel@nelsonmullins.com'],
            ['nelsonmullins.com', 'John F. Haley', 'john.haley@nelsonmullins.com'],
            ['hka.com', 'Michael Laming', 'michaellaming@hka.com'],
            ['ferrere.com', 'Néstor Loizaga', 'nloizaga@ferrere.com'],
            ['ferrere.com', 'Agustin Mayer', 'amayer@ferrere.com'],
            ['velo-legal.com', 'Juan Antonio Boyd Alemán', 'jboyd@velo-legal.com'],
            ['squairlaw.com', 'Maria Lancri', 'mlancri@squairlaw.com'],
            ['shoosmiths.com', 'Alastair Peet', 'alastair.peet@shoosmiths.com'],
            ['hka.com', 'Juan Francisco Nasser', 'juanfrancisconasser@hka.com'],
            ['sorainen.com', 'Rudolfs Engelis', 'rudolfs.engelis@sorainen.com'],
            ['sorainen.com', 'Toomas Prangli', 'toomas.prangli@sorainen.com'],
            ['lexvalor.com', 'Juan Francisco Almeida', 'jalmeida@lexvalor.com'],
            ['caseslacambra.com', 'José Manuel Llanos', 'josemanuel.llanos@caseslacambra.com'],
            ['oppenhoff.eu', 'Edder Cifuentes', 'edder.cifuentes@oppenhoff.eu'],
            ['stellexlaw.com', 'Anthony Yang', 'anthony.yang@stellexlaw.com'],
            ['dechert.com', 'Bernardo L. Piereck', 'bernardo.piereck@dechert.com'],
            ['az.cl', 'Macarena Waidele', 'mwaidele@az.cl'],
            ['gleisslutz.com', 'Christian Cascante', 'christian.cascante@gleisslutz.com'],
            ['gleisslutz.com', 'Andrea Leufgen', 'andrea.leufgen@gleisslutz.com'],
            ['bakerbotts.com', 'María Carolina Durán', 'mariacarolina.duran@bakerbotts.com'],
            ['hugheshubbard.com', 'Diego Durán de la Vega', 'diego.duran@hugheshubbard.com'],
            ['draperllc.com', 'Matthew E. Draper', 'matthew.draper@draperllc.com'],
            ['gentile.law', 'Marta Batalla Eguidazu', 'martabatalla@gentile.law'],
            ['lloredacamacho.com', 'Gustavo Tamayo', 'gtamayo@lloredacamacho.com'],
            ['mwe.com', 'Ignacio Zabala', 'izabala@mwe.com'],
            ['eof.com.ar', 'Cecilia Cook', 'cookc@eof.com.ar'],
            ['mqmgld.com', 'Camilo Martinez', 'cmartinez@mqmgld.com'],
            ['torys.com', 'Gillian Dingl', 'gdingle@torys.com'],
            ['bustamantefabara.com', 'Juan José Holguín', 'jholguin@bustamantefabara.com'],
            ['bustamantefabara.com', 'José Antonio Fabara', 'jafabara@bustamantefabara.com'],
            ['guerrero.cl', 'Camila Costagliola', 'ccostagliola@guerrero.cl'],
            ['vieirarezende.com.br', 'Rafael de Moraes Amorim', 'ramorim@vieirarezende.com.br'],
            ['withersworldwide.com', 'Christina Baltz', 'christina.baltz@withersworldwide.com'],
            ['sorainen.com', 'Laimonas Skibarka', 'laimonas.skibarka@sorainen.com'],
            ['raedas.com', 'Joana Rego', 'jrego@raedas.com'],
            ['swlaw.com', 'Manuel Rajunov​​​​', 'mrajunov@swlaw.com'],
            ['mwe.com', 'Maria Cristina Rosales del Prado', 'mcrosalesdelprado@mwe.com'],
            ['blg.com', 'Martin Abadi', 'mabadi@blg.com'],
            ['debrauw.com', 'Marnix Leijten', 'marnix.leijten@debrauw.com'],
            ['roschier.com', 'Ami Paanajärvi', 'ami.paanajarvi@roschier.com'],
            ['roschier.com', 'Jens Bengtsson', 'jens.bengtsson@roschier.com'],
            ['apoyoconsultoria.com', 'Vincent Poirier-Garneau', 'vpoirier@apoyoconsultoria.com'],
            ['mololamken.com', 'Jennifer Schubert', 'jschubert@mololamken.com'],
            ['ropesgray.com', 'David H. Saltzman', 'david.saltzman@ropesgray.com'],
            ['phrlegal.com', 'Juan Camilo de Bedout', 'juan.debedout@phrlegal.com'],
            ['phrlegal.com', 'Silvia Velasquez', 'silvia.velasquez@phrlegal.com'],
            ['berettagodoy.com', 'Joaquin Carrillo', 'carrillo@berettagodoy.com'],
            ['marval.com', 'Soledad Riera', 'solr@marval.com'],
            ['berettagodoy.com', 'Juan Sonoda', 'sonoda@berettagodoy.com'],
            ['dscasahierro.pe', 'Charles Castle', 'ccastle@dscasahierro.pe'],
            ['mccannfitzgerald.com', 'Stephen Holst', 'stephen.holst@mccannfitzgerald.com'],
            ['belex.com', 'Barbara Concolino', 'barbara.concolino@belex.com'],
            ['lefosse.com', 'Felipe Gibson', 'felipe.gibson@lefosse.com'],
            ['hugheshubbard.com', 'Emilio Saiz Gaela Flores', 'emilio.saiz@hugheshubbard.com'],
            ['skadden.com', 'Lorenzo Corte', 'lorenzo.corte@skadden.com'],
            ['skadden.com', 'Paola Lozano', 'paola.lozano@skadden.com'],
            ['blplegal.com', 'Anneliss Wohlers', 'awohlers@blplegal.com'],
            ['chaffetzlindsey.com', 'James Hosking', 'james.hosking@chaffetzlindsey.com'],
            ['chaffetzlindsey.com', 'Matilde Flores', 'matilde.flores@chaffetzlindsey.com'],
            ['ropesgray.com', 'Matt Posthuma', 'matthew.posthuma@ropesgray.com'],
            ['ropesgray.com', 'Matthew J. Byron', 'matthew.byron@ropesgray.com'],
            ['ioepik.legal', 'Antonio Montes', 'amontes@ioepik.legal'],
            ['ioepik.legal', 'Walter Bodden', 'jwalter@ioepik.legal'],
            ['advant-nctm.com', 'Luca Cavagnaro', 'luca.cavagnaro@advant-nctm.com'],
            ['jpadvisors.do', 'Jennifer Beauchamps Haché', 'jbeauchamps@jpadvisors.do'],
            ['squairlaw.com', 'Sophie Gabillot', 'sgabillot@squairlaw.com'],
            ['squairlaw.com', 'Julia Kalfon', 'jkalfon@squairlaw.com'],
            ['cgsh.com', 'Jonathan Mendes de Oliveira', 'jmendesdeoliveira@cgsh.com'],
            ['darroisvilley.com', 'Charles Martin', 'cmartin@darroisvilley.com'],
            ['darroisvilley.com', 'Didier Theophile', 'dtheophile@darroisvilley.com'],
            ['darroisvilley.com', 'Matthieu Brochier', 'mbrochier@darroisvilley.com'],
            ['hugheshubbard.com', 'Daniel H. Weiner', 'daniel.weiner@hugheshubbard.com'],
            ['hugheshubbard.com', 'Gaela Gehring Flores', 'gaela.gehringflores@hugheshubbard.com'],
            ['skadden.com', 'Jose Vivanco', 'jose.vivanco@skadden.com'],
            ['dietz@bindergroesswang.at', 'Christine Dietz', 'dietz@bindergroesswang.at'],
            ['bpvabogados.com', 'Jordi Biosca', 'jbiosca@bpvabogados.com'],
            ['dietz@bindergroesswang.at', 'Isabelle Innerhofer', 'innerhofer@bindergroesswang.at'],
            ['squairlaw.com', 'Charles - Louis Pierron', 'clpierron@squairlaw.com'],
            ['wienerboerse.at', 'Matthias Szabo', 'matthias.szabo@wienerboerse.at'],
            ['wienerboerse.at', 'Hector Mohedano', 'hector.mohedano@wienerboerse.at'],
            ['foxmandal.in', 'Shourya Mandal', 'shourya.mandal@foxmandal.in'],
            ['lw.com', 'Marcela Ruenes', 'marcela.ruenes@lw.com'],
            ['lw.com', 'Pedro Rufino Carvalho', 'pedro.rufinocarvalho@lw.com'],
            ['gide.com', 'Alexandra Munoz', 'alexandra.munoz@gide.com'],
            ['blankrome.com', 'Timothy Hruby', 'tim.hruby@blankrome.com'],
            ['blankrome.com', 'Eric Parnes', 'eric.parnes@blankrome.com'],
            ['drewnapier.com', 'Benjamin Gaw ', 'benjamin.gaw@drewnapier.com'],
            ['bennettjones.com', 'Linda Misetich Dann', 'misetichdannl@benettjones.com'],
            ['bennettjones.com', 'Ian C. Michel', 'michaeli@bennettjones.com'],
            ['agycia.cl', 'Ignacio Arteaga', 'iarteaga@agycia.cl'],
            ['agycia.cl', 'Luciano Cruz', 'lcruz@agycia.cl'],
            ['stibbe.com', 'Claire-Marie Darnand', 'clairemarie.darnand@stibbe.com'],
            ['stibbe.com', 'Erik Valgaeren', 'erik.valgaeren@stibbe.com'],
            ['stibbe.com', 'Michael Molenaars', 'michael.molenaars@stibbe.com'],
            ['fundacionpombo.org', 'Carmen Pombo Morales', 'cpombo@fundacionpombo.org'],
            ['fundacionpombo.org', 'Francisco Gil Durán', 'fgil@ga-p.com'],
            ['fundacionpombo.org', 'Iñigo Erlaiz Cotelo', 'ierlaiz@ga-p.com'],
            ['svz.fr', 'Emmanuelle Vicidomini', 'evicidomini@svz.fr'],
            ['svz.fr', 'Oscar Da Silva', 'odasilva@svz.fr'],
            ['bsfllp.com', 'John Lyons', 'jlyons@bsfllp.com'],
            ['wbd-us.com', ' Jose Luis Vittor', 'joseluis.vittor@wbd-us.com'],
            ['wbd-us.com', 'Francisco Balduzzi', 'francisco.balduzzi@wbd-us.com'],
            ['dechert.com', 'Laura Brank', 'laura.brank@dechert.com'],
            ['debevoise.com', 'Sergio Torres', 'storres@debevoise.com'],
            ['prcp.com.pe', 'Juan José Cauvi', 'jjc@prcp.com.pe'],
            ['blakes.com', 'Bob Wooder', 'bob.wooder@blakes.com'],
            ['blakes.com', 'Kate McGilvray', 'kate.mcgilvray@blakes.com'],
            ['blakes.com', 'Paul Stepak', 'paul.stepak@blakes.com'],
            ['lennox.nl', 'Gerard Endedijk', 'gerard.endedijk@lennox.nl'],
            ['lennox.nl', 'Maarten Vink', 'maarten.vink@lennox.nl'],
            ['hengeler.com', 'Andreas Hoger', 'andreas.hoger@hengeler.com'],
            ['lacourte.com', 'Serge Tatar', 'tatar@lacourte.com'],
            ['lacourte.com', 'Jean-Yves Charriau', 'charriau@lacourte.com'],
            ['fangdalaw.com', 'Peng Tan', 'peng.tan@fangdalaw.com'],
            ['mololamken.com', 'Anden Chow', 'achow@mololamken.com'],
            ['syls.com.ar', 'Eduardo Ferrari', 'ef@syls.law'],
            ['bu.com.co', 'José Francisco Mafla', 'jmafla@bu.com.co'],
            ['tpa.com.ve', 'Valentina Cabrera', 'vcabrera@tpa.com.ve'],
            ['uria.com', 'Carolina Rozo', 'carolina.rozo@ppulegal.com'],
            ['khaitanco.com', 'Sanjeev Kapoor', 'sanjeev.kapoor@khaitanco.com'],
            ['khaitanco.com', 'Manavendra Mishra', 'manavendra.mishra@khaitanco.com'],
            ['siac.org.sg', 'Adriana Uson', 'adrianauson@siac.org.sg'],
            ['advant-beiten.com', 'Luca Cavagnaro', 'luca.cavagnaro@advant-nctm.com'],
            ['www.pillsburylaw.com', 'Robert L. Sills', 'robert.sills@pillsburylaw.com'],
            ['www.pillsburylaw.com', 'Ben Clark', 'ben.clark@pillsburylaw.com'],
            ['blankrome.com', 'Joanne E. Osendarp', 'joanne.osendarp@blankrome.com'],
            ['raedas.com', 'William Teddy', 'wteddy@raedas.com'],
            ['raedas.com', 'Eric Wheeler ', 'ewheeler@raedas.com'],
            ['hengeler.com', 'Annika Clauss', 'annika.clauss@hengeler.com'],
            ['hsf.com', 'Eduard Dougherty', 'edward.dougherty@hsf.com'],
            ['marval.com', 'Soledad Riera', 'solr@marval.com'],
            ['hsf.com', 'Nigel Farr', 'nigel.farr@hsf.com'],
            ['nishimura.com', 'Tatsuya Tanigawa', 't.tanigawa@nishimura.com'],
            ['nishimura.com', 'Makoto Shimizu', 'm.shimizu@nishimura.com'],
            ['prcp.com.pe', 'José Antonio Payet', 'jap@prcp.com.pe'],
            ['fangdalaw.com', 'Flora Qian', 'flora.qian@fangdalaw.com'],
            ['fangdalaw.com', 'Yingjie Wang', 'yingjie.wang@fangdalaw.com'],
            ['prcp.com.pe', 'Cecilia Gonzáles', 'cgg@prcp.com.pe'],
            ['www.dwpv.com', 'Richard Fridman', 'rfridman@dwpv.com'],
            ['nelsonmullins.com', 'Leandro Vivarelli Molina', 'leandro.molina@nelsonmullins.com'],
            ['fangdalaw.com', 'Gil Zhang', 'gil.zhang@fangdalaw.com'],
            ['cesconbarrieu.com.br', 'Gabriel Seijo Leal de Figueiredo', 'gabriel.seijo@cesconbarrieu.com.br'],
            ['galicia.com', 'Cecilia Azar', 'cazar@galicia.com.mx'],
            ['ioepik.legal', 'Donald Dubon', 'ddubon@ioepik.legal']
        ];
        foreach ($delegates as $key => $delegate) {
            Delegate::create([
                'original' => $delegate[0],
                'name' => $delegate[1],
                'email' => $delegate[2],
            ]);
        }
    }
}
